[workspace]
resolver = "2"
members = ["crates/msx-disk", "crates/mediaexplorer-gui"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"
repository = "https://github.com/sndpl/msx-media-explorer"
authors = ["Sandy Pleyte"]

[workspace.lints.clippy]
all = "warn"

[profile.release]
lto = "thin"
strip = true
